In [3]:
import os
import tensorflow as tf
from tensorflow import keras

In [4]:
path = '/kaggle/input/data-mnist/mnist.npz'
(x_train, y_train), _ = tf.keras.datasets.mnist.load_data(path=path)
print(x_train[:2])
print(y_train[:5])
print(f'panjang x_train: {len(x_train)}')
print(f'panjang y_train: {len(y_train)}')

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[5 0 4 1 9]
panjang x_train: 60000
panjang y_train: 60000


In [6]:
data_shape = x_train.shape
print(f'terdapat {data_shape[0]} sampel, dengan ukuran ({data_shape[1]}, {data_shape[2]})')

terdapat 60000 sampel, dengan ukuran (28, 28)


In [17]:
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if logs.get('accuracy') >= 0.99:
            print('\nAkurasi sudah mencapai 99%, jadi training dihentikan')
            self.model.stop_training = True

In [21]:
from tensorflow.keras.datasets import mnist

def train_mnist():
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train = x_train / 255.0
    x_test = x_test / 255.0
    callbacks = myCallback()
    
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    
    model.compile(optimizer='adam',
                   loss='sparse_categorical_crossentropy',
                   metrics=['accuracy'])
    
    model.fit(x_train, y_train, epochs=10, callbacks=[callbacks], verbose=1)
    
    return model, x_test, y_test

In [22]:
model, x_test, y_test = train_mnist()

Epoch 1/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2583 - accuracy: 0.9265
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1154 - accuracy: 0.9653
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0800 - accuracy: 0.9751
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0591 - accuracy: 0.9814
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0456 - accuracy: 0.9855
Epoch 6/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0371 - accuracy: 0.9884
Epoch 7/10
1867/1875 [============================>.] - ETA: 0s - loss: 0.0285 - accuracy: 0.9908
Akurasi sudah mencapai 99%, jadi training dihentikan
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0284 - accuracy: 0.9908


In [25]:
print(model)

In [41]:
print(x_test.shape)
print(x_test[0].shape)

i = 11

input_data = x_test[i].reshape(1, 28, 28)
prediksi = model.predict(input_data)
maksimal = max(prediksi[0])
prediksi_list = list(prediksi[0])
index_prediksi = prediksi_list.index(maksimal)
print(f'hasil prediksi: {index_prediksi}')

(10000, 28, 28)
(28, 28)
1/1 [==============================] - 0s 21ms/step
hasil prediksi: 6
