In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('/kaggle/input/oranges-vs-grapefruit/citrus.csv')
print(df)

            name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]


In [13]:
print(len(df))

10000


In [14]:
# Mengubah nama menjadi numerik
df.name[df.name == 'orange'] = 0
df.name[df.name == 'grapefruit'] = 1

/tmp/ipykernel_32/1523731220.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.name[df.name == 'orange'] = 0
/tmp/ipykernel_32/1523731220.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.name[df.name == 'grapefruit'] = 1


In [15]:
print(df)

     name  diameter  weight  red  green  blue
0       0      2.96   86.76  172     85     2
1       0      3.91   88.05  166     78     3
2       0      4.42   95.17  156     81     2
3       0      4.47   95.60  163     81     4
4       0      4.48   95.76  161     72     9
...   ...       ...     ...  ...    ...   ...
9995    1     15.35  253.89  149     77    20
9996    1     15.41  254.67  148     68     7
9997    1     15.59  256.50  168     82    20
9998    1     15.92  260.14  142     72    11
9999    1     16.45  261.51  152     74     2

[10000 rows x 6 columns]


In [16]:
# Mengubah dataframe menjadi array
dataset = df.values
print(dataset)

[[0 2.96 86.76 172 85 2]
 [0 3.91 88.05 166 78 3]
 [0 4.42 95.17 156 81 2]
 ...
 [1 15.59 256.5 168 82 20]
 [1 15.92 260.14 142 72 11]
 [1 16.45 261.51 152 74 2]]


In [17]:
X = dataset[:, 1:6]
print(X)

[[2.96 86.76 172 85 2]
 [3.91 88.05 166 78 3]
 [4.42 95.17 156 81 2]
 ...
 [15.59 256.5 168 82 20]
 [15.92 260.14 142 72 11]
 [16.45 261.51 152 74 2]]


In [18]:
y = dataset[:, 0]
print(y)

[0 0 0 ... 1 1 1]


In [20]:
# Normalization
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
print(min_max_scaler)
print(X_scale)

MinMaxScaler()
[[0.         0.         0.74025974 0.63529412 0.        ]
 [0.07042254 0.00738197 0.66233766 0.55294118 0.01851852]
 [0.10822832 0.04812589 0.53246753 0.58823529 0.        ]
 ...
 [0.93624907 0.97133047 0.68831169 0.6        0.33333333]
 [0.96071164 0.99216023 0.35064935 0.48235294 0.16666667]
 [1.         1.         0.48051948 0.50588235 0.        ]]


In [22]:
# pisahkan data training dan testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)
print(len(X_train), len(X_test), len(Y_train), len(Y_test))

7000 3000 7000 3000


In [23]:
import numpy as np
Y_train = Y_train.astype(np.float32)
Y_test = Y_test.astype(np.float32)

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
model = Sequential([
    Dense(32, activation='relu', input_shape=(5,)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [26]:
model.compile(optimizer='sgd',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [27]:
model.fit(X_train, Y_train, epochs=100, verbose=1)

Epoch 1/100
219/219 [==============================] - 1s 2ms/step - loss: 0.6624 - accuracy: 0.7694
Epoch 2/100
219/219 [==============================] - 0s 2ms/step - loss: 0.5977 - accuracy: 0.8904
Epoch 3/100
219/219 [==============================] - 0s 2ms/step - loss: 0.5243 - accuracy: 0.9070
Epoch 4/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4353 - accuracy: 0.9173
Epoch 5/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3499 - accuracy: 0.9237
Epoch 6/100
219/219 [==============================] - 0s 2ms/step - loss: 0.2864 - accuracy: 0.9233
Epoch 7/100
219/219 [==============================] - 0s 2ms/step - loss: 0.2463 - accuracy: 0.9254
Epoch 8/100
219/219 [==============================] - 0s 2ms/step - loss: 0.2223 - accuracy: 0.9263
Epoch 9/100
219/219 [==============================] - 0s 2ms/step - loss: 0.2073 - accuracy: 0.9271
Epoch 10/100
219/219 [==============================] - 0s 2ms/step - loss: 0.1985 - accura

In [28]:
model.evaluate(X_test, Y_test)

94/94 [==============================] - 0s 1ms/step - loss: 0.1754 - accuracy: 0.9270


[0.17544712126255035, 0.9269999861717224]